const { Item } = require('../models');

const itemData = [
  { item_name: '85th Anniversary Pedestal Cake Plate', category_id: 1 },
  { item_name: '85th Anniversary Large Disk Pitcher', category_id: 1 },
  { item_name: 'Large Covered Casserole', category_id: 2 },
  { item_name: 'Small Covered Casserole / Tortilla Warmer', category_id: 2 },
  { item_name: 'Individual Casserole', category_id: 2 },
  { item_name: 'Ramekin', category_id: 2 },
  { item_name: 'Heart Ramekin', category_id: 2 },
  { item_name: 'Rectangular Baker', category_id: 2 },
  { item_name: 'Square Baker', category_id: 2 },
  { item_name: 'Baking / Pizza Tray', category_id: 2 },
  { item_name: 'Deep Dish Pie Baker', category_id: 2 },
  { item_name: 'Fruit / Salsa Bowl', category_id: 3 },
  { item_name: 'Small Bowl', category_id: 3 },
  { item_name: 'Medium Bowl', category_id: 3 },
  { item_name: 'Large Bowl', category_id: 3 },
  { item_name: 'Stacking Cereal Bowl', category_id: 3 },
  { item_name: 'Large Bistro Bowl', category_id: 3 },
  { item_name: 'Medium Bistro Bowl', category_id: 3 },
  { item_name: 'Small Bistro Bowl', category_id: 3 },
  { item_name: 'Gusto Bowl', category_id: 3 },
  { item_name: 'Hostess Bowl', category_id: 3 },
  { item_name: 'Pedestal Bowl', category_id: 3 },
  { item_name: 'Mixing Bowl Set', category_id: 3 },
  { item_name: 'Square Soup Bowl', category_id: 3 },
  { item_name: 'Pasta Bowl', category_id: 3 },
  { item_name: 'Rim Soup Bowl', category_id: 3 },
  { item_name: '4 Piece Baking Bowl Set', category_id: 3 },
  { item_name: '3 Piece Baking Bowl Set', category_id: 3 },
  { item_name: 'Utensil Crock', category_id: 4 },
  { item_name: 'Small Canister', category_id: 4 },
  { item_name: 'Medium Canister', category_id: 4 },
  { item_name: 'Large Canister', category_id: 4 },
  { item_name: 'Utility Jam Jar', category_id: 4 },
  { item_name: 'Covered Butter Dish', category_id: 5 },
  { item_name: 'Sugar Packet Caddy', category_id: 5 },
  { item_name: 'Creamer', category_id: 5 },
  { item_name: 'Sauce Boat', category_id: 5 },
  { item_name: 'Spoon Rest', category_id: 5 },
  { item_name: 'Salt and Pepper Set', category_id: 5 },
  { item_name: 'Trivet', category_id: 5 },
  { item_name: 'Egg Plate / Tray', category_id: 5 },
  { item_name: 'Tea Cup', category_id: 6 },
  { item_name: 'Saucer', category_id: 6 },
  { item_name: 'Mug', category_id: 6 },
  { item_name: 'Java Mug', category_id: 6 },
  { item_name: 'Jumbo Cup', category_id: 6 },
  { item_name: 'Bud Vase', category_id: 7 },
  { item_name: 'Large Pitcher', category_id: 7 },
  { item_name: 'Small Pitcher', category_id: 7 },
  { item_name: 'Tea Pot', category_id: 7 },
  { item_name: 'Millineum Vase #1', category_id: 7 },
  { item_name: 'Millineum Vase #2', category_id: 7 },
  { item_name: 'Millineum Vase #3', category_id: 7 },
  { item_name: '12pc Bistro Place Setting', category_id: 8 },
  { item_name: '12pc Classic Place Setting', category_id: 8 },
  { item_name: '3pc Bistro Place Setting', category_id: 8 },
  { item_name: '3pc Classic Place Setting', category_id: 8 },
  { item_name: '4pc Place Setting', category_id: 8 },
  { item_name: '5pc Place Setting', category_id: 8 },
  { item_name: 'Dinner Plate', category_id: 9 },
  { item_name: 'Luncheon Plate', category_id: 9 },
  { item_name: 'Salad Plate', category_id: 9 },
  { item_name: 'Chop Plate', category_id: 9 },
  { item_name: 'Holiday Plate', category_id: 9 },
  { item_name: 'Pedestal Cake Plate', category_id: 11 },
  { item_name: '2pc Chip-N-Dip Set', category_id: 11 },
  { item_name: 'Small Bread Tray', category_id: 11 },
];

const seedItem = () => Item.bulkCreate(itemData);

module.exports = seedItem;